"""Add departure and transportation fields to travel_plans

Revision ID: 06579011db90
Revises: 
Create Date: 2025-10-13 09:10:12.641108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06579011db90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空字段
    op.add_column('travel_plans', sa.Column('departure', sa.String(length=100), nullable=True))
    op.add_column('travel_plans', sa.Column('transportation', sa.String(length=50), nullable=True))
    
    # 为现有数据设置默认值
    op.execute("UPDATE travel_plans SET departure = '北京' WHERE departure IS NULL")
    
    # 将departure字段设为非空
    op.alter_column('travel_plans', 'departure', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_plans', 'transportation')
    op.drop_column('travel_plans', 'departure')
    # ### end Alembic commands ###
