"""Add traveler info fields to travel_plan

Revision ID: 5e917d2b7820
Revises: 06579011db90
Create Date: 2025-10-16 17:29:03.895249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e917d2b7820'
down_revision: Union[str, None] = '06579011db90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plans', sa.Column('travelers', sa.Integer(), nullable=True))
    op.add_column('travel_plans', sa.Column('ageGroups', sa.JSON(), nullable=True))
    op.add_column('travel_plans', sa.Column('foodPreferences', sa.JSON(), nullable=True))
    op.add_column('travel_plans', sa.Column('dietaryRestrictions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_plans', 'dietaryRestrictions')
    op.drop_column('travel_plans', 'foodPreferences')
    op.drop_column('travel_plans', 'ageGroups')
    op.drop_column('travel_plans', 'travelers')
    # ### end Alembic commands ###
