"""
数据库初始化所需的种子数据
"""

DEFAULT_USERS = [
    {
        "id": 1,
        "username": "admin",
        "email": "admin@lxai.com",
        "full_name": "系统管理员",
        "hashed_password": "$2b$12$w8GM49ePhxbCzT6qWNnvHOx/VHCh0MOmbFjUpFUG8Y4OTDmeM0Iq.",
        "role": "admin",
        "is_verified": True,
        "is_active": True,
    },
    {
        "id": 2,
        "username": "demo_user",
        "email": "demo@lxai.com",
        "full_name": "演示用户",
        "hashed_password": "$2b$12$w8GM49ePhxbCzT6qWNnvHOx/VHCh0MOmbFjUpFUG8Y4OTDmeM0Iq.",
        "role": "user",
        "is_verified": True,
        "is_active": True,
    },
]

DESTINATIONS = [
    {
        "name": "北京",
        "country": "中国",
        "city": "北京",
        "region": "华北",
        "latitude": 39.9042,
        "longitude": 116.4074,
        "description": "中华人民共和国的首都，历史文化名城",
        "highlights": ["天安门广场", "故宫", "长城", "颐和园"],
        "best_time_to_visit": "春季和秋季",
        "popularity_score": 9.5,
        "safety_score": 9.0,
        "cost_level": "medium",
        "images": [
            "https://example.com/beijing1.jpg",
            "https://example.com/beijing2.jpg",
        ],
    },
    {
        "name": "上海",
        "country": "中国",
        "city": "上海",
        "region": "华东",
        "latitude": 31.2304,
        "longitude": 121.4737,
        "description": "中国最大的经济中心城市",
        "highlights": ["外滩", "东方明珠", "豫园", "南京路"],
        "best_time_to_visit": "春季和秋季",
        "popularity_score": 9.2,
        "safety_score": 8.8,
        "cost_level": "high",
        "images": [
            "https://example.com/shanghai1.jpg",
            "https://example.com/shanghai2.jpg",
        ],
    },
    {
        "name": "广州",
        "country": "中国",
        "city": "广州",
        "region": "华南",
        "latitude": 23.1291,
        "longitude": 113.2644,
        "description": "广东省省会，岭南文化中心",
        "highlights": ["珠江夜游", "陈家祠", "白云山", "上下九"],
        "best_time_to_visit": "冬季和春季",
        "popularity_score": 8.8,
        "safety_score": 8.5,
        "cost_level": "medium",
        "images": [
            "https://example.com/guangzhou1.jpg",
            "https://example.com/guangzhou2.jpg",
        ],
    },
    {
        "name": "深圳",
        "country": "中国",
        "city": "深圳",
        "region": "华南",
        "latitude": 22.5431,
        "longitude": 114.0579,
        "description": "中国改革开放的前沿城市",
        "highlights": ["世界之窗", "欢乐谷", "大梅沙", "华强北"],
        "best_time_to_visit": "全年",
        "popularity_score": 8.5,
        "safety_score": 8.7,
        "cost_level": "high",
        "images": [
            "https://example.com/shenzhen1.jpg",
            "https://example.com/shenzhen2.jpg",
        ],
    },
    {
        "name": "杭州",
        "country": "中国",
        "city": "杭州",
        "region": "华东",
        "latitude": 30.2741,
        "longitude": 120.1551,
        "description": "人间天堂，西湖美景",
        "highlights": ["西湖", "灵隐寺", "雷峰塔", "千岛湖"],
        "best_time_to_visit": "春季和秋季",
        "popularity_score": 9.0,
        "safety_score": 8.9,
        "cost_level": "medium",
        "images": [
            "https://example.com/hangzhou1.jpg",
            "https://example.com/hangzhou2.jpg",
        ],
    },
]

ATTRACTIONS = [
    {
        "destination_name": "北京",
        "name": "天安门广场",
        "category": "历史建筑",
        "description": "中华人民共和国的象征",
        "address": "北京市东城区天安门广场",
        "latitude": 39.9042,
        "longitude": 116.4074,
        "opening_hours": {
            "周一": "全天开放",
            "周二": "全天开放",
            "周三": "全天开放",
            "周四": "全天开放",
            "周五": "全天开放",
            "周六": "全天开放",
            "周日": "全天开放",
        },
        "ticket_price": 0,
        "currency": "CNY",
        "rating": 4.7,
        "review_count": 12580,
        "features": ["免费参观", "历史意义", "拍照圣地"],
        "accessibility": ["无障碍通道", "轮椅租赁"],
        "contact_info": {"电话": "010-65132277"},
        "images": [
            "https://example.com/tiananmen1.jpg",
            "https://example.com/tiananmen2.jpg",
        ],
        "website": "https://www.tiananmen.org.cn",
    },
    {
        "destination_name": "北京",
        "name": "故宫博物院",
        "category": "博物馆",
        "description": "明清两代的皇家宫殿",
        "address": "北京市东城区景山前街4号",
        "latitude": 39.9163,
        "longitude": 116.3972,
        "opening_hours": {
            "周一": "08:30-17:00",
            "周二": "08:30-17:00",
            "周三": "08:30-17:00",
            "周四": "08:30-17:00",
            "周五": "08:30-17:00",
            "周六": "08:30-17:00",
            "周日": "08:30-17:00",
        },
        "ticket_price": 60,
        "currency": "CNY",
        "rating": 4.8,
        "review_count": 9876,
        "features": ["世界文化遗产", "古建筑", "文物展览"],
        "accessibility": ["无障碍通道", "语音导览"],
        "contact_info": {"电话": "010-85007421"},
        "images": [
            "https://example.com/gugong1.jpg",
            "https://example.com/gugong2.jpg",
        ],
        "website": "https://www.dpm.org.cn",
    },
    {
        "destination_name": "上海",
        "name": "外滩",
        "category": "观光景点",
        "description": "上海的标志性景观",
        "address": "上海市黄浦区中山东一路",
        "latitude": 31.2397,
        "longitude": 121.4994,
        "opening_hours": {
            "周一": "全天开放",
            "周二": "全天开放",
            "周三": "全天开放",
            "周四": "全天开放",
            "周五": "全天开放",
            "周六": "全天开放",
            "周日": "全天开放",
        },
        "ticket_price": 0,
        "currency": "CNY",
        "rating": 4.6,
        "review_count": 15678,
        "features": ["免费参观", "夜景美丽", "历史建筑"],
        "accessibility": ["无障碍通道"],
        "contact_info": {"电话": "021-63213579"},
        "images": [
            "https://example.com/waitan1.jpg",
            "https://example.com/waitan2.jpg",
        ],
        "website": "https://www.shanghai.gov.cn",
    },
    {
        "destination_name": "杭州",
        "name": "西湖",
        "category": "自然景观",
        "description": "人间天堂的美景",
        "address": "浙江省杭州市西湖区",
        "latitude": 30.2741,
        "longitude": 120.1551,
        "opening_hours": {
            "周一": "全天开放",
            "周二": "全天开放",
            "周三": "全天开放",
            "周四": "全天开放",
            "周五": "全天开放",
            "周六": "全天开放",
            "周日": "全天开放",
        },
        "ticket_price": 0,
        "currency": "CNY",
        "rating": 4.9,
        "review_count": 23456,
        "features": ["免费参观", "自然美景", "文化底蕴"],
        "accessibility": ["无障碍通道", "游船服务"],
        "contact_info": {"电话": "0571-87969691"},
        "images": [
            "https://example.com/xihu1.jpg",
            "https://example.com/xihu2.jpg",
        ],
        "website": "https://www.hangzhou.gov.cn",
    },
]

RESTAURANTS = [
    {
        "destination_name": "北京",
        "name": "全聚德烤鸭店",
        "cuisine_type": "北京菜",
        "description": "百年老字号烤鸭店",
        "address": "北京市东城区前门大街30号",
        "latitude": 39.9042,
        "longitude": 116.4074,
        "opening_hours": {
            "周一": "11:00-22:00",
            "周二": "11:00-22:00",
            "周三": "11:00-22:00",
            "周四": "11:00-22:00",
            "周五": "11:00-22:00",
            "周六": "11:00-22:00",
            "周日": "11:00-22:00",
        },
        "price_range": "人均 ¥200-¥300",
        "rating": 4.5,
        "review_count": 5678,
        "features": ["传统老字号", "适合聚餐", "有包间"],
        "contact_info": {
            "电话": "010-65112418",
            "地址": "北京市东城区前门大街30号",
        },
        "menu_highlights": ["北京烤鸭", "炸酱面", "豆汁"],
        "images": [
            "https://example.com/quanjude1.jpg",
            "https://example.com/quanjude2.jpg",
        ],
        "website": "https://www.quanjude.com.cn",
    },
    {
        "destination_name": "上海",
        "name": "小笼包店",
        "cuisine_type": "上海菜",
        "description": "正宗上海小笼包",
        "address": "上海市黄浦区南京东路123号",
        "latitude": 31.2304,
        "longitude": 121.4737,
        "opening_hours": {
            "周一": "10:00-22:00",
            "周二": "10:00-22:00",
            "周三": "10:00-22:00",
            "周四": "10:00-22:00",
            "周五": "10:00-22:00",
            "周六": "10:00-22:00",
            "周日": "10:00-22:00",
        },
        "price_range": "人均 ¥40-¥60",
        "rating": 4.3,
        "review_count": 3456,
        "features": ["传统小吃", "价格实惠", "外卖服务"],
        "contact_info": {
            "电话": "021-63212345",
            "地址": "上海市黄浦区南京东路123号",
        },
        "menu_highlights": ["小笼包", "生煎包", "糖醋排骨"],
        "images": [
            "https://example.com/xiaolongbao1.jpg",
            "https://example.com/xiaolongbao2.jpg",
        ],
        "website": "https://www.xiaolongbao.com",
    },
    {
        "destination_name": "广州",
        "name": "粤菜馆",
        "cuisine_type": "粤菜",
        "description": "正宗广东菜",
        "address": "广东省广州市天河区珠江新城",
        "latitude": 23.1291,
        "longitude": 113.2644,
        "opening_hours": {
            "周一": "11:00-23:00",
            "周二": "11:00-23:00",
            "周三": "11:00-23:00",
            "周四": "11:00-23:00",
            "周五": "11:00-23:00",
            "周六": "11:00-23:00",
            "周日": "11:00-23:00",
        },
        "price_range": "人均 ¥150-¥250",
        "rating": 4.7,
        "review_count": 7890,
        "features": ["正宗粤菜", "环境优雅", "服务周到"],
        "contact_info": {
            "电话": "020-12345678",
            "地址": "广东省广州市天河区珠江新城",
        },
        "menu_highlights": ["白切鸡", "叉烧", "煲仔饭"],
        "images": [
            "https://example.com/yuecai1.jpg",
            "https://example.com/yuecai2.jpg",
        ],
        "website": "https://www.yuecai.com",
    },
]

ACTIVITY_TYPES = [
    {
        "name": "观光游览",
        "description": "参观景点和地标建筑",
        "category": "cultural",
        "duration_range": {"min": 2, "max": 8},
        "difficulty_level": "easy",
        "age_restriction": {"min": 0, "max": 100},
    },
    {
        "name": "户外运动",
        "description": "登山、徒步等户外活动",
        "category": "outdoor",
        "duration_range": {"min": 4, "max": 12},
        "difficulty_level": "medium",
        "age_restriction": {"min": 8, "max": 65},
    },
    {
        "name": "文化体验",
        "description": "博物馆、艺术馆参观",
        "category": "cultural",
        "duration_range": {"min": 1, "max": 6},
        "difficulty_level": "easy",
        "age_restriction": {"min": 0, "max": 100},
    },
    {
        "name": "美食体验",
        "description": "品尝当地特色美食",
        "category": "food",
        "duration_range": {"min": 1, "max": 3},
        "difficulty_level": "easy",
        "age_restriction": {"min": 0, "max": 100},
    },
    {
        "name": "购物娱乐",
        "description": "购物和娱乐活动",
        "category": "entertainment",
        "duration_range": {"min": 2, "max": 6},
        "difficulty_level": "easy",
        "age_restriction": {"min": 0, "max": 100},
    },
]

